# Generated by Django 5.2.7 on 2025-11-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('Img', models.TextField(null=True)),
            ],
        ),
    ]
