# Generated by Django 5.2.8 on 2025-11-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
