# Generated by Django 5.2.8 on 2025-11-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
