# Generated by Django 5.2.8 on 2025-11-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0004_alter_anime_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_to_watch', models.ManyToManyField(related_name='plan_to_watch_users', to='Anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anime.user')),
                ('watching', models.ManyToManyField(related_name='watching_users', to='Anime.anime')),
            ],
        ),
    ]
